# Generated by Django 5.0.4 on 2024-05-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scales',
            new_name='Scale',
        ),
    ]
