# Generated by Django 5.0.4 on 2024-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_admin', '0002_rename_scales_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='scale',
            name='hotel_Main_Img',
            field=models.ImageField(default='x', upload_to='images/'),
        ),
    ]
