# Generated by Django 5.0.4 on 2024-05-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_admin', '0003_scale_hotel_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='hotel_Main_Img',
        ),
        migrations.AddField(
            model_name='scale',
            name='scale_img',
            field=models.ImageField(default='x', upload_to='scales/'),
        ),
    ]
