# Generated by Django 5.0.4 on 2024-05-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_admin', '0004_remove_scale_hotel_main_img_scale_scale_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='scale_img',
        ),
        migrations.AddField(
            model_name='scale',
            name='img_guitar',
            field=models.ImageField(default='x', upload_to='scales/guitar'),
        ),
        migrations.AddField(
            model_name='scale',
            name='img_keyboard',
            field=models.ImageField(default='x', upload_to='scales/keyboard'),
        ),
    ]
