# Generated by Django 5.0.4 on 2024-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_admin', '0006_rename_img_guitar_scale_guitar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
