# Generated by Django 5.0.4 on 2024-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_admin', '0007_alter_scale_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
