# Generated by Django 5.0.4 on 2024-09-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_admin', '0009_chord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='guitar_image',
            field=models.ImageField(default='x', upload_to='chords/guitar'),
        ),
        migrations.AlterField(
            model_name='chord',
            name='keyboard_image',
            field=models.ImageField(default='x', upload_to='chords/keyboard'),
        ),
    ]
